### PR TITLE
1st ES translate

### PR DESCRIPTION
**Pull request by mrtngrsbch**
my 1st translate

### CODE REVIEW

**Comment by o1lab** [comment]
@mrtngrsbch : thank you for the PR.

Could you please sign your git commits with name (no aliases) and email.

Please check this on how to sign : https://github.com/nocodb/nocodb/blob/master/contribute/HowToApplyLicense.md#how-to-sign-your-work

or if you want to sign already submitted commits - it can be done like this

https://user-images.githubusercontent.com/5435402/125443638-2ca54520-d72a-439b-93bc-4e2c692c759b.png

**Comment by mrtngrsbch** [comment]
> @mrtngrsbch : thank you for the PR.
> 
> Could you please sign your git commits with name (no aliases) and email.
> 
> Please check this on how to sign : https://github.com/nocodb/nocodb/blob/master/contribute/HowToApplyLicense.md#how-to-sign-your-work
> 
> or if you want to sign already submitted commits - it can be done like this
> 
> https://user-images.githubusercontent.com/5435402/125443638-2ca54520-d72a-439b-93bc-4e2c692c759b.png

Hi @o1lab,

Excuse me but I have used the github web interface and I don't see any way to apply the requirements you indicate.

**Comment by pixplix** [comment]
Please check my comments, thank you for help us with translations!

**Comment by o1lab** [comment]
I am unsure on how to sign from web interface. I've taken the essence of changes in my commit. So please fork the repo and create PR for changes next time. 

@all-contributors please add @mrtngrsbch for code

**Comment by mrtngrsbch** [comment]
> I am unsure on how to sign from web interface. I've taken the essence of changes in my commit. So please fork the repo and create PR for changes next time.
> 
> @all-contributors please add @mrtngrsbch for code

Hi @o1lab,
Sorry for the inconvenience, I was away without my equipment. Even so, this is the first time I have had these requirements for a pull request.

**Pull request closed without merging**
