### PR TITLE
Chore: Update eslint rules

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

- Add `consistent-type-imports` rule ( https://typescript-eslint.io/rules/consistent-type-imports/ )

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
Lots of conflicts due to renaming. Suggested to create a new PR. That would be faster.

**Comment by pranavxc** [comment]
> Lots of conflicts due to renaming. Suggested to create a new PR. That would be faster.

Rebased and pushed :+1:

**Comment by wingkwong** [comment]
Put it on hold for PR 5262 and an extra sync. I'll merge it after that.

**Comment by pranavxc** [comment]
@wingkwong : resolved conflict and applied lint fix.

**Comment by wingkwong** [comment]
All tests are passed. I'll merge after an upstream sync.

**Pull request merged**
