### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by bmscmoreira**

### CODE REVIEW

**Review by pranavxc — CHANGES_REQUESTED** [review]
Please sign your commits, for more information about signing commits refer: https://github.com/nocodb/nocodb/blob/master/contribute/HowToApplyLicense.md

you can do something like

```
# sign the last 1 comit
git rebase HEAD~1 --signoff

# force push your changes 
git push -f
```

**Comment by bmscmoreira** [comment]
Hope to have done things right this time with my GPG key

**Comment by pranavxc** [comment]
out of 2 one of the commits is not signed, maybe you have to do

```
git rebase HEAD~2 --signoff
```

**Comment by bmscmoreira** [comment]
> 
> 
> out of 2 one of the commits is not signed, maybe you have to do
> 
> ```
> git rebase HEAD~2 --signoff
> ```

Hope this is now ok. Sorry, first time with these signing requirements :)

**Comment by pranavxc** [comment]
@all-contributors please add @bmscmoreira for code

**Pull request merged**
