### PR TITLE
fix: Grid view - Single-select/Multi-select related bugs and improvements

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

re #4573

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by dstala** [comment]
- [ ] click on single select cell. move cursor to left or right. triggers horizontal scroll instead of moving to adjacent cell

**Review by dstala — CHANGES_REQUESTED** [review]
https://www.loom.com/share/8319e8d769c34551833e81002c2230e3

**Comment by dstala** [comment]
- [x] multi-select : first click should enter `select mode`; currently its going to `edit mode`
- [ ] low priority : support for use of tab along with enter key for option selection
- [ ] low priority : while adding new option from cell, press tab is inserting `create option` menu at end of options list

**Comment by dstala** [comment]
@pranavxc 

- [ ] fix alignment of select fields in gallery view
  
Screenshot 2023-02-01 at 8 52 34 PM

- [ ] form view (shared incognito) - multi-select drop down option missing
  
Screenshot 2023-02-01 at 8 55 47 PM
Screenshot 2023-02-01 at 8 56 28 PM

**Review by wingkwong — APPROVED** [review]

**Review by dstala — APPROVED** [review]

**Pull request merged**
