### PR TITLE
Fix getColVal in parserHelpers.ts -> col index can be 0 -> so check only that its not undefined

### PR DESCRIPTION
**Pull request by semmjon**
## Change Summary

Excel / CSV Import not working with auto type detection.
The getColVal returns the whole row for the first col, because the index is null.

So i do instead of:
```
row && col ? row[col] : row
```
this
```
row && col !== undefined ? row[col] : row
```

## Change type

- [X ] fix: (bug fix for the user, not a fix to a build script)

## Test/ Verification

Tested locally.

## Error - Image:
image

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
please don't commit unrelated files.

**Comment by semmjon** [comment]
sorry, it was probably unintentional .

**Comment by wingkwong** [comment]
The expected file changes should be just 1. You are removing the entire package file now.

**Comment by semmjon** [comment]
ok got it I'll be more careful next time ;)

**Comment by wingkwong** [comment]
Now you removed the fix :D

**Comment by wingkwong** [comment]
Looks fine now.

**Pull request merged**
