### PR TITLE
Enhancement: UI improvements 

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

- Add transition for menu(filter/sort/fields)
- Include icon within select(fileter/sort)
- Show loader while loading data(grid/gallery)
- Remove announcement

re #2150 

https://user-images.githubusercontent.com/61551451/170499118-931e9ae6-e31a-48db-a6f5-f370edebae0c.mov

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
if announcement is not in use, shall we also delete `announcement.vue` and related code in `app.js`?

**Comment by pranavxc** [comment]
> if announcement is not in use, shall we also delete `announcement.vue` and related code in `app.js`?

Will remove those parts as well

**Review by wingkwong — COMMENTED** [review]
Something wrong with MM List? See the failed cypress tests.

dataList :: error: select "language"."language_id" as "LanguageId", "language"."name" as "Name", "language"."last_update" as "LastUpdate" from "language" where (((("language_id" = $1)))) order by "language_id" asc limit $2 - invalid input syntax for integer: "undefined"

**Comment by pranavxc** [comment]
> Something wrong with MM List? See the failed cypress tests.
> 
> dataList :: error: select "language"."language_id" as "LanguageId", "language"."name" as "Name", "language"."last_update" as "LastUpdate" from "language" where (((("language_id" = $1)))) order by "language_id" asc limit $2 - invalid input syntax for integer: "undefined"

It was related to belongs to relation, if belongs to column is empty then it was returning an empty object, looks like that's caused the error.

**Pull request merged**
