### PR TITLE
Fix "Base Editor: Not allowed" error on sign

### PR DESCRIPTION
**Pull request by rohittp0**
## Change Summary
closes: #8194 
The permission being checked in the frontend and that being checked by the corresponding controller were different. Updated frontend to align with backend.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

### CODE REVIEW

**Review by dstala — APPROVED** [review]

**Comment by jessystecroix717** [comment]
u

**Comment by mertmit** [comment]
I don’t think this resolves the issue, also explanation in body is wrong because we have different acl for frontend & backend.

We need to take an in-depth look on our handling here, so lets go through this:
- there is one root level which is org
- every base is within org
- org role is inherited only if no role set at base level
- base order is kept at base entity itself *** -> this is the crucial part
So logically a org creator sounds like it should be able to reorder the bases but it is not confirmed for an org creator to have access to all bases (unless he is super-admin)

This causes two issues:
- There will be some invisible bases for an org creator, so order will be unpredictable on change
- Even if you are org creator, if you have assigned a lower role for a specific base you won’t be able to change order as you don’t allowed to update

So the change only hide the initial issue, but if you try to reorder (base with editor role) using that role you can see the error.

cc @dstala

**Comment by rohittp0** [comment]
@mertmit So are you suggesting removing base reorder permission for org-level creators? Or should that permission be replaced with base edit, as users with base edit access would be guaranteed to have reordered permission?

**Comment by dstala** [comment]
@mertmit 
- allow users with ORG-Creator (OC) to re-order any bases (including the one's in which this user has base-viewer access).
- prevent ORG-Viewer (OV) from re-ordering bases.

Can base-reorder request from OC be given an exception on Base viewer permission level to still over ride base order information?

In cloud, we apply same principle to WS-Creators. WS-Creator (+ WS Owner) will be able to apply re-order to any base.

We understand that, such action would be
- visible to everyone. reorder applies to all
- and depending on the bases that user has access to, the end visible result might differ.

**Comment by mertmit** [comment]
Yes we can provide an exception.
Even I would suggest creating a new endpoint for this operation reason being right now we calculate order from frontend and provide it with payload but some of the bases might not be visible for the user causing miss calculations, in the new endpoint we can have a payload like `{ id: string; before_id?: string; after_id?: string }` then we can calculate order based on provided anchor base.
This way we will avoid having duplicate orders for bases.

**Pull request closed without merging**
