### PR TITLE
fix(gui-v2): attachments not loading in shared view

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by dstala** [comment]
@bcakmakoglu able to drag-drop files now. files submitted are not visible in grid view (attachment cell is empty even after hard refresh). rest of the details filled out in the form are visible.

will this be tracked in a separate PR?

**Comment by bcakmakoglu** [comment]
@dstala 
There seems to be an issue with saving the files but I can't really tell why it's happening 😞 
@wingkwong Do you have an idea, why the files aren't saved properly? When I check the Network tab it sends the attachment as [object object] instead of the actual attachment data (which I see when I use the Gui V1).

Maybe @pranavxc can help with the issue? It doesn't seem related to the Attachment component itself but somewhere the value gets processed and somehow turned into "nothing" instead of staying a File or something.

**Review by dstala — APPROVED** [review]

**Review by dstala — CHANGES_REQUESTED** [review]
- [x] Form attachment submission verified, could see the file in grid view
- [x] Failed to submit a form with an attachment field, without including any attachments.
  
Screenshot 2022-08-23 at 9 21 22 PM

**Comment by bcakmakoglu** [comment]
@dstala I updated the PR

**Review by dstala — APPROVED** [review]

**Pull request merged**
