### PR TITLE
Update ko.json

### PR DESCRIPTION
**Pull request by jiione**
fix korean translation
/pakages/nc-gui/lang/ko.json
https://docs.google.com/spreadsheets/d/1KrjYor2VQAi0mOvZjlw95bIfyyFNuhE5RsJ56vObjvE/edit?usp=sharing

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by wingkwong** [comment]
@jiione Thanks for the contribution. Please refer [here](https://github.com/nocodb/nocodb/blob/master/scripts/contribute/HowToApplyLicense.md#how-to-sign-your-previous-work) to sign your work back.

**Comment by jiione** [comment]
OK! I'm done fixing it!

**Comment by wingkwong** [comment]
감사합니다 :)

**Comment by o1lab** [comment]
@all-contributors please add @jiione for code

**Pull request merged**
