### PR TITLE
Add page to explain role permissions, user mgmt

### PR DESCRIPTION
**Pull request by candideu**
Hello! I'm new to this, so forgive me if this is the incorrect way to contribute.

I wanted to add a page that explained the user permissions because I couldn't find this info anywhere. The tables were largely inspired from this page: https://support.airtable.com/hc/en-us/articles/202887099-Permissions-overview.

Please complete the table with check-marks and x's to indicate what the various roles can or can't do.

## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [x] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by o1lab** [comment]
This is a good idea. We've something internally of this order. Will merge with those changes.

**Comment by wingkwong** [comment]
@candideu Thanks for the contribution. Please refer [here](https://github.com/nocodb/nocodb/blob/master/scripts/contribute/HowToApplyLicense.md#how-to-sign-your-previous-work) to sign your work back.

**Comment by o1lab** [comment]
@wingkwong : the commit looks like was done from git GUI (says verified) - we 've to work around to skip if its verified in DCO check.

**Comment by wingkwong** [comment]
@o1lab True. Lemme work on it later.

**Comment by o1lab** [comment]
sure @wingkwong

**Comment by pranavxc** [comment]
@all-contributors please add @candideu for code

**Pull request merged**
