### PR TITLE
fix: consider `NC_S3_ENDPOINT` besides `NC_S3_REGION`

### PR DESCRIPTION
**Pull request by salim-b**
## Change Summary

Thanks to https://github.com/nocodb/nocodb/pull/8886 and follow-up changes, the S3 plugin now supports any S3-compatible storage provider. So if `NC_S3_ENDPOINT` is provided, `NC_S3_REGION` should not be necessary anymore (region is part of the endpoint URL). But currently, the plugin configuration via env variables is skipped if `NC_S3_REGION` is not provided even if `NC_S3_ENDPOINT` as well as the other necessary `NC_S3_*` vars are set. I think this change should fix that, but I'm not really familiar with the internals and didn't test it. Maybe additional changes are required.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [x] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Untested.

## Additional information / screenshots (optional)

Additionally, in S3 plugin configuration UI, the "region" field should be made optional if "endpoint" is provided. Ideally, a tooltip or something should indicate that "endpoint" takes precedence over "region", i.e. "region" is in fact ignored once "endpoint" is provided.

### CODE REVIEW

**Comment by salim-b** [comment]
@DarkPhoenix2704 Could you have a look at this PR on occasion? It's only about a small quality-of-life improvement :)

**Comment by DarkPhoenix2704** [comment]
Can you resolve the conflicts?

**Comment by salim-b** [comment]
> Can you resolve the conflicts @salim-b ?

@DarkPhoenix2704 Done. :)

**Review by DarkPhoenix2704 — APPROVED** [review]

**Comment by DarkPhoenix2704** [comment]
l merge once the tests are green

**Pull request merged**
