### PR TITLE
feat: implement view sections

### PR DESCRIPTION
**Pull request by vanutp**
## Change Summary

ref: #145

Implemented view sections. On the backend `section` string column added to views table.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)

## Test/ Verification

Wrote a basic test creating a section and moving a view into it.

### CODE REVIEW

**Comment by Shagulka** [comment]
Nice

**Comment by dstala** [comment]
Screenshot 2022-12-26 at 2 11 47 PM

**Comment by o1lab** [comment]
Thanks for the PR. Before taking issue with large scope - get in touch with one of the maintainers pls.

**Comment by vanutp** [comment]
Thanks for the quick response.

> Thanks for the PR. Before taking issue with large scope - get in touch with one of the maintainers pls.

Sorry, will do in the future.



Currently it's implemented using a string column in the views table on the backend. So no information about the section exists in the database until a view is added into it. Should I add a separate table for sections?

**Pull request closed without merging**
