### PR TITLE
fix: Persian language moving across table

### PR DESCRIPTION
**Pull request by mertmit**
## Change Summary

Re https://github.com/nocodb/nocodb/issues/2240

## Change type

- [x] fix: (bug fix for the user, not a fix to a build script)

### CODE REVIEW

**Comment by wingkwong** [comment]
@okaeiz Please help verify based on the above image

**Comment by o1lab** [comment]
Verified.

**Comment by okaeiz** [comment]
Is it done or I should test the image?

**Comment by okaeiz** [comment]
It's OK. Thanks for making it great. ✅

**Pull request merged**
