### PR TITLE
fix: expanded row nav fix

### PR DESCRIPTION
**Pull request by DarkPhoenix2704**
## Change Summary

Closes https://github.com/nocodb/nocodb/issues/10070

## Change type

- [x] fix: (bug fix for the user, not a fix to a build script)

### CODE REVIEW

**Comment by c2006878** [comment]
Is the fix done? Still having the same issue

**Review by rameshmane7218 — APPROVED** [review]

**Comment by c2006878** [comment]
@rameshmane7218 @DarkPhoenix2704   I know. But i found after merged, it has the same issue. such as this link: https://app.nocodb.com/#/w3oez0rl/px04ans9b3dfqpp/mqmh48wtebgt32y

**Comment by c2006878** [comment]
sometimes refresh the page will also have this issue

**Comment by DarkPhoenix2704** [comment]
Hi @c2006878 

The issue is fixed in NocoDB Cloud. The fix will be available in next Bug Fix Release

**Pull request merged**
