### PR TITLE
Bug fix for issue #5438, resolved text-overflow with text-wrapping

### PR DESCRIPTION
**Pull request by nith2001**
## Change Summary

This PR resolves [Issue ##5438](https://github.com/nocodb/nocodb/issues/5438) regarding the buggy view of the text on the form view, specifically the form input label and the form help text. Both were resolved by setting `word-break` to `break-all` and allowing wrapping to occur in these text fields. Along with that, I noticed another bug regarding text overflow with the required red error text that shows up under required form inputs when left empty. That is fixed here as well.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Here's some pictures of it working, and the text is now wrapping. No truncation or overflow is occurring.

Screen Shot 2023-04-23 at 9 12 34 PM
Screen Shot 2023-04-24 at 12 20 20 PM

## Additional information / screenshots (optional)

This is my first PR to NocoDB, so please let me know if there's anything I can fix for y'all!

### CODE REVIEW

**Review by dstala — CHANGES_REQUESTED** [review]
Thanks @nith2001 for the PR. Some observations recorded here. Request you to include if you can.

- [ ] Survey mode, button overlaps text
    
Screenshot 2023-04-25 at 10 11 22 AM



- [ ] Will be good if we can enable wrap text for title & sub-title during form creation dialog window
  
Screenshot 2023-04-25 at 10 24 49 AM

**Comment by nith2001** [comment]
Oo, good finds. And I'm guessing if the input text was just one long unbroken string, there might be overflow as well. I'll take a look!

**Comment by nith2001** [comment]
Okay, I'm working on enabling wrap text for title & sub-title during form creation, and it seems like the only way to make that happen is to switch from using an `<a-input>` tag to a custom editable `<div>` tag. So far that process is looking okay, but there may be some slightly altered behavior with how the placeholder text appears and disappears onFocus vs. onInput potentially, so we'll see. Still new to Vue, so I'm learning as I go.

**Comment by nith2001** [comment]
Hey, I noticed a lot of inconsistencies with where Cmd-A or Ctrl-A works and doesn't work. Like, it works in the title and description of the form but not the field input, etc. Do we want to maintain this behavior? Asking because this capability is disabled while I'm trying to enable wrapping in the title and description.

**Comment by nith2001** [comment]
Okay, here is an update regarding wrapping the heading and sub-heading. In order for this to be viable, there are two ways for it to be implemented, either the CSS way or the Javascript way. The CSS way would require hard-coding a `<div>` tag to behave as a <textarea> tag but without scrolling in order to support dynamic resizing. I was able to get that to work but the placeholder text started to become very janky. The other route would be the Javascript way, which would modify the div element's height as the text began filling up. 

I'm inclined to go with the CSS route, but it's definitely going to be rather time-consuming and personally I think the payoff is very minimal. @dstala would you like me to try and prioritize the other problem instead?

**Review by nith2001 — COMMENTED** [review]
(sorry, misclick, did not mean to send this, but I can't delete it now)

**Comment by nith2001** [comment]
Small code refactor to ensure other areas of the site are unaffected.

**Review by dstala — CHANGES_REQUESTED** [review]
- [ ] Help text missing in shared form view (normal mode and survey mode)

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.106.1**
  

Screenshot 2023-05-04 at 12 43 33 PM

**Comment by nith2001** [comment]
https://github.com/nocodb/nocodb/discussions/5590

**Comment by nith2001** [comment]
Well, unless someone can explain how to switch my node version on NocoDB, I replicated @dstala exact conditions as stated above (except for node version, I'm using 18) and the help text was not missing.

**Comment by dstala** [comment]
@nith2001 
You have raised PR for nith2001:develop to be merged. I noticed another branch 'wrapping' under nith2001. The changes under it worked fine (help text was visible as intended). Please double check.

**Comment by nith2001** [comment]
The `wrapping` branch was where I was keeping some changes before merging it into my `develop` branch. It's merged now, so `develop` has my latest code.

**Comment by dstala** [comment]
> The `wrapping` branch was where I was keeping some changes before merging it into my `develop` branch. It's merged now, so `develop` has my latest code. Feel free to take a look!

Still the same. Please double check if you have merged all changes from wrapping to develop. 
Help text remains visible in `wrapping` but missing in `develop`

**Comment by nith2001** [comment]
Weird, that doesn't make any sense. My merge from `wrapping` to `develop` is right here:
Screen Shot 2023-05-10 at 1 23 54 PM

And if I were to try another merge, this is what I see on Github:
Screen Shot 2023-05-10 at 1 21 10 PM

However, I was able to verify the bug that you mentioned, and I personally have no clue how to solve it, because there's legit no visible code left to merge.

**Comment by nith2001** [comment]
Ok, I just tested out the NocoDB main `develop` branch code and the problem with the help text seems to exist there too, which means it wasn't a problem on my end. I'm confused why my `wrapping` code supposedly was okay but not in `develop` even though both branches are identical. @dstala , do you have any thoughts?

**Review by dstala — APPROVED** [review]

**Comment by wingkwong** [comment]
@dstala FYI. Issue5633 is an separate issue. Unrelated to the changes done in this PR. I'll fix 5633 soon.

**Comment by dstala** [comment]
@nith2001 rebase to latest develop please. will check if issue still persists

**Comment by nith2001** [comment]
Sorry, I was trying to rebase but it wasn't working (most likely I was doing something wrong I'm new to rebasing, and would appreciate it if you could give a short explanation of what I should've done). Feel free to check if the issue still persists!

**Comment by wingkwong** [comment]
@nith2001 Right now you've included lots of unrelated changes. Here's what you can do.

First, please undo your incorrect rebase. `a4e0eafbc` is the last commit before you rebased

```
git reset a4e0eafbc
```

then force push once

```
git push -f
```

To sync your forked branch, you can simply go to your repo and click this button

image

**Comment by nith2001** [comment]
Awesome! Sorry about the inconvenience, I normally would've just clicked sync as well but I was confused by the rebase instruction. Did what you said, and I have this right now:
Screen Shot 2023-05-18 at 10 26 16 PM

**Comment by wingkwong** [comment]
@nith2001 This looks fine to me. Rerunning the CI again. Let's wait for the result.

**Comment by nith2001** [comment]
Status update on this? I'm guessing it's not my code that's breaking it, right?

**Comment by dstala** [comment]
> Any update on this? I'm guessing it's not my code that's breaking it, right?

I will check it again today. rebase to the latest develop please.

**Comment by nith2001** [comment]
Only noticeable thing was that there was a merge conflict I had to resolve in `packages/nc-gui/components/smartsheet/header/Cell.vue` on Line 55.

My original code didn't have the `!hideMenu` thing but the code I was rebasing to my code included it, so I just accepted that but kept my changes for maintaining wrapping.

**Comment by nith2001** [comment]
Damn, still not passing...maybe it is because of my changes?

**Comment by nith2001** [comment]
Messed up and accidentally discarded my commits on my repo rather than clicking Update Branch when doing the rebase update. Didn't mean to close PR and I had to force push my code back up. Can

**Review by pranavxc — APPROVED** [review]

**Pull request merged**
