### PR TITLE
Remove password character requirements

### PR DESCRIPTION
**Pull request by jgillich**
## Change Summary

Removes password character requirements as per https://github.com/nocodb/nocodb/issues/242

Not sure how to classify this correctly, could be both feat or fix :shrug: 

Also found some dead links so I fixed them

## Change type

- [X] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

### CODE REVIEW

**Comment by wingkwong** [comment]
@jgillich please rebase. For the broken links, they have been fixed in `develop`. The expected file change in this PR should be just `packages/nocodb-sdk/src/lib/passwordHelpers.ts`.

**Comment by jgillich** [comment]
@wingkwong Done

**Review by wingkwong — COMMENTED** [review]
`progress` is redundant

**Comment by jgillich** [comment]
I left the whole structure as-is in case someone wants to add more validations in the future, but sure, I can remove it

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
