### PR TITLE
 eyeSlash icon is not shown in form #5798

### PR DESCRIPTION
**Pull request by DIWAKARKASHYAP**
## Change Summary

- closes: https://github.com/nocodb/nocodb/issues/5798

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [x] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by DIWAKARKASHYAP** [comment]
please check issue #5798

**Comment by o1lab** [comment]
Thanks for contributing. Please sign CLA above

**Comment by DIWAKARKASHYAP** [comment]
> Thanks for contributing. Please sign CLA above

done

**Review by wingkwong — CHANGES_REQUESTED** [review]
The expected behaviour is that the icon will only show when you hover a form entry. See below screenshot - I'm hovering the first entry.

image

By default, we set `opacity-0` so that all remove icons will be invisible at the beginning. When we hover `.nc-editable` block, the icon will be visible. Previously we were using `MdiEyeOffOutline` so the scss would work. However, at some point we changed to `iconMap.eyeSlash` causing the reported issue.

Therefore, removing `opacity-0` is not a correct fix. Instead, you just need to update the scss part in the same file.

https://github.com/nocodb/nocodb/blob/7550bdde93fcb290aae4e96c6d325da346e34547/packages/nc-gui/components/smartsheet/Form.vue#L839-L843

Simply change to the following - then it should work

```scss
.nc-editable:hover {
  :deep(.nc-field-remove-icon) {
    @apply opacity-100;
  }
}
```

**Comment by DIWAKARKASHYAP** [comment]
got it , 
thanks , i will make the changes

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
