### PR TITLE
Call stored procedures

### PR DESCRIPTION
**Pull request by zbynekrybicka**
Hi. Here is solution of call procedures (no functions).
I will be pleasured for any feedback. Especially in safety.

### CODE REVIEW

**Comment by o1lab** [comment]
@zbynekrybicka : thank you.

Could you please write some tests under [test](https://github.com/o1lab/xmysql/tree/master/tests) directory. 

If there are no stored procedures existing in sample.sql - create couple of them in sample.sql.

**Comment by o1lab** [comment]
hey @zbynekrybicka - I see you have added tests. I think loading sql changes before test is making it fail. Do you want to have a relook into it ?

**Comment by zbynekrybicka** [comment]
Sorry, I lost my source db and I can't connect to testing db.
You need only create procedure in SQL and call POST /_proc/*procname* and params are in body.

**Comment by zbynekrybicka** [comment]
I apologize for delay. It's complete.

**Pull request closed without merging**
