### PR TITLE
Add deploy on Railway button

### PR DESCRIPTION
**Pull request by FarazPatankar**
This PR adds a `Deploy on Railway` button which allows users to deploy NocoDB to Railway in just one click.

### CODE REVIEW

**Comment by o1lab** [comment]
Need code signing, see [here](https://github.com/nocodb/nocodb/blob/master/contribute/HowToApplyLicense.md)

**Comment by FarazPatankar** [comment]
Hey @o1lab, haven't done this before so not quite sure what the process is. Do I need to create an additional commit with the `-s` flag or is there a better way to do this?

**Comment by o1lab** [comment]
Below was how one of our users did it.

Screen Shot 2021-07-13 at 16 52 47

**Comment by FarazPatankar** [comment]
Better now?

**Comment by FarazPatankar** [comment]
I had another quick question, @o1lab. How can I also get the button on the website? Should I just PR it or are there any additional things that need to be done?

button@2x

**Comment by o1lab** [comment]
Hey @FarazPatankar, Thanks for the PR.

I 've this question with railway though. I tried deploying it on railway after creating an account on it - but it is asking for accessing my github repos! Not sure that's seamless or expected experience. Im not sure why repo access is required to deploy something on railway ? Is this not taking our docker image from dockerhub or its trying to build from nocodb or nocodb-seed ?

Screen Shot 2021-07-14 at 13 34 34

**Comment by FarazPatankar** [comment]
The starter uses [this repository](https://github.com/railwayapp-starters/nocodb) (a fork of `nocodb-seed-heroku`) to create the deployment.

Github access it required because the way it works is we create a GH repo for you in your account/org so any changes you make can be deployed automatically.

**Comment by o1lab** [comment]
I am not clear the user's intention was to create a repository within their own account on "1-Click deploy to railway". This is not same as in heroku 1-Click deployment. May be railway should really reconsider how this is done. I will have to comment unfortunately for that reason.

**Comment by FarazPatankar** [comment]
I understand that it's different from the way Heroku works and why you'd consider it to not be a one-click deploy but removing it entirely isn't right either, no?

I could add a different section and explain how it works? Because it's still a super convenient way to deploy NocoDB.

**Comment by FarazPatankar** [comment]
Tagging in case you missed this, @o1lab. Happy to discuss this further (if required) on another medium if that makes things easier.

**Comment by candideu** [comment]
Hi @o1lab ! In light of Heroku's recent announcement to [phase out free plans starting November 28, 2022](https://blog.heroku.com/next-chapter), will the decision to add a Railway deployment button to the README, website, and docs (https://github.com/nocodb/nocodb/issues/1265) be reconsidered?

I use Railway to deploy my NocoDB instance, and as someone who's not the most technical, I definitely prefer it over deploying on Heroku. On Railway, I can connect a domain for free and can access my entire database from the application much easier.

Other open-source apps like [Listmonk](https://listmonk.app/), [Cusdis](https://github.com/djyde/cusdis), [Authorizer](https://authorizer.dev/), [Umami](https://umami.is/docs/getting-started), [Cal.com](https://github.com/calcom/cal.com), etc. have Railway deploy buttons on their sites, repos, and/or docs. Some have even [partnered](https://railway.app/open-source-kickback) with Railway.

[Pikapods](https://www.pikapods.com/apps), an open-source hosting platform, also offers quick deployment of NocoDB. I've seen

**Pull request merged**
