### PR TITLE
vue3: Follow up on User management

### PR DESCRIPTION
**Pull request by mustafapc19**
Ref: [Comment](https://github.com/nocodb/nocodb/issues/2825#issuecomment-1210200214)

- Fixed wrong roles
- Now roles pill shows color
- Added `isUIAllowed` to hide `Invite team` button when the user is not privileged.

### CODE REVIEW

**Comment by dstala** [comment]
- [ ] `Copy invite URL` didn't store URL to clipboard
  
Screenshot 2022-08-10 at 8 20 47 PM

- [ ] Console & API error on `Editor` sign-in
  
Screenshot 2022-08-10 at 8 22 34 PM
Screenshot 2022-08-10 at 8 23 38 PM

- [ ] Editor, Commenter, Viewer role should not see
  - Project tree
    - Right click menu
    - 3-dot menu 
  - Right Nav Bar 
    - View create 
    - Copy view
    - Webhook 
  - Tool bar
    - Share view 
    - More actions menu should have only download CSV & Upload CSV
  - Tab
    - Add / Import menu
    - Column create
  - Project menu : Preview 

TBD
Comments to be verified after Expand row is integrated

**Comment by mustafapc19** [comment]
@dstala 

For the third point (ACL stuff), should we do this in this PR? I only included ACL in user management. I think its better to do all the others in a separate PR.

**Comment by dstala** [comment]
@mustafapc19 URL copy for new user verified- working

**Review by dstala — APPROVED** [review]
Changes verified

**Pull request merged**
