### PR TITLE
fix(gui-v2): table rename

### PR DESCRIPTION
**Pull request by wingkwong**
## Change Summary

ref: #3086 (v2)

- add table name length validation logic to tableCreate & tableUpdate
- DOMPurify table name for tableCreate & tableUpdate
- update title, table_name & underlying db table name when renaming the table in NocoDB UI (ref: #2668)

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

- Create Sheet2
- Rename to Sheet2x
- Create Sheet2

image

### CODE REVIEW

**Comment by dstala** [comment]
Verified length limitations & trailing space limitations for the table name.
On SQLite Root DB, I was still able to create two projects with the same name

**Comment by dstala** [comment]
> Verified length limitations & trailing space limitations for the table name. On SQLite Root DB, I was still able to create two projects with the same name

SQLite project name's case sensitive. Was allowed to create `x` and `X`; on the project screen, both were displayed as `X`. should be ok I think - we can ignore them.

**Review by dstala — APPROVED** [review]

**Comment by wingkwong** [comment]
Needa take a look at cypress.

**Comment by dstala** [comment]
> Needa take a look at cypress.

Backend has an error; see if it helps

```
tableUpdate :: Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [id] query: select * from `nc_projects_v2` where `id` = ? and `deleted` = ? limit ?
    at QueryCompiler_SQLite3.toSQL (/home/runner/work/nocodb/nocodb/packages/nocodb/node_modules/knex/lib/query/compiler.js:98:13)
    at Builder.toSQL (/home/runner/work/nocodb/nocodb/packages/nocodb/node_modules/knex/lib/query/builder.js:97:44)
    at /home/runner/work/nocodb/nocodb/packages/nocodb/node_modules/knex/lib/runner.js:31:36
    at /home/runner/work/nocodb/nocodb/packages/nocodb/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.getWithInfo (/home/runner/work/nocodb/nocodb/packages/nocodb/src/lib/models/Project.ts:152:21)
    at tableUpdate (/home/runner/work/nocodb/nocodb/packages/nocodb/src/lib/meta/api/tableApis.ts:224:19)
    at /home/runner/work/nocodb/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:14
PATCH /api/v1/db/meta/tables/md_z3wmkxmv8vmeud 400 166 - 53.868 ms
```

**Comment by wingkwong** [comment]
@dstala Did you capture it from Github Action log?

**Comment by dstala** [comment]
> @dstala Did you capture it from Github Action log?

Yes, that's correct

**Review by pranavxc — APPROVED** [review]

**Comment by wingkwong** [comment]
Findings:
- in v1, grid view is empty after renaming a table
- in v2, it works fine

**Comment by wingkwong** [comment]
Skipping v1 cypress.

**Pull request merged**
