### PR TITLE
Undo select option removal

### PR DESCRIPTION
**Pull request by ketewan**
## Change Summary

Since option removal is a destructive operation in can be a good idea to warn a user beforehead

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

image

### CODE REVIEW

**Comment by o1lab** [comment]
Clicking cancel wont save it. Having a confirm for a leaf level option will come in between good ux.

**Comment by ketewan** [comment]
@o1lab You suggest saving/cancelling option removal at once on a leaf level, not waiting for a main "save" button to be clicked, or?

**Comment by ketewan** [comment]
@o1lab 
As we discussed, I removed the popup solution and changed it to have temporarily deleted options with the possibility to undo before save

https://user-images.githubusercontent.com/31967149/212680221-7d302c4f-f69f-437d-8f79-bf9b292b0789.mov

note: I don't like the solution much because of 2 sources of true (renderedOptions and options) and the need to sync them manually, but otherwise it will end up either in deep watch for renderedOptions (if we add watch to change the original options), which is non-performant, or big refactoring (a better option would be to normalize the data before saving, but with the current code it would either make the code messier or require more general refactoring, and I don't think the task is worth it)

**Comment by o1lab** [comment]
@pranavxc

**Review by pranavxc — APPROVED** [review]

**Pull request merged**
