### PR TITLE
feat(gui-v2): form view

### PR DESCRIPTION
**Pull request by wingkwong**
## Change Summary

ref: #2630 

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

image

## Additional information / screenshots (optional)

TODO:

- need a better algorithm for calculating `order`. (currently if two orders are similar, it would fail.)

### CODE REVIEW

**Comment by dstala** [comment]
@wingkwong 

Form view
feat/gui-v2-form-view

some of the issues may not be under current PR scope. recording it here nevertheless

Issues
- [ ] Toolbar should have only `Share view` button. Disable rest (Pranav?)
- [ ] v1: click column entry present in `Form Fields` menu, it was being added to end of form; doesn't work in v2
- [ ] `Add new field` to table; try to drag and drop new field to Form view. Fails. 
- [ ] Default form view, no additional configuration; submit. Click on form-view button in right navigation bar doesn't open form view again
- [ ] Copy `From view` from Right Navigation Bar is broken (Burak?); copy option creates new view. doesn't copy view configuration


Verified
- Title & description persist
- Column label, help text persist
- `Remove all` : doesn't remove fields marked as required
- `Add all` 
- Fields re-order / remove; persists
- Submit message
- Submit another form
- Show blank form after 5 seconds
- SMTP not configured warning


Pending
- Shared form (WIP)
- SMTP configuration

**Comment by wingkwong** [comment]
@dstala revised those three issues.

@pranavxc @bcakmakoglu please review when you have time.

Thanks.

**Comment by dstala** [comment]
@wingkwong 

- [ ] Delete a view, we should fall back to the default grid view; currently, the view display persists on the screen
- [ ] UX: Form width, we can cut it by 30% (close to v1); if it's easy, let's bring back a layout similar to v1 (shadow effect for form, kind of shows good elevation)
- [ ] Can't `drag and drop` field after marking it as required

**Comment by wingkwong** [comment]
@dstala Fixed form view related issues. As spoken, others will be handled in corresponding PRs.

**Review by dstala — APPROVED** [review]

**Pull request merged**
