### PR TITLE
fix: prevent system fields from getting deleted manually

### LINKED ISSUE #8236: 🐛 Bug: Primary key shouldn't be deleted manually.
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- The table's System Fields can be hidden or shown, and system fields can be also deleted! Although system fields can not be edited.
image
- If users delete the Id, which is the primary key of the table, the system will throw out Error: "Update not allowed for table which doesn't have primary key."
image
image
- This is not reasonable. System fields can be shown, but cannot be deleted or edited, I think.

### Desired Behavior

x

### Project Details

- docker build
- version 0.205.0
- mysql8.0

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by sreehari2003**
## Change Summary

Provide summary of changes with issue number if any.
- Closes #8236 
- Video https://sreehari-jayaraj.neetorecord.com/watch/0ce672be-cc7f-444d-95ad-c5c241f7453b

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated the logic in the menu to correctly display the delete option for columns based on specific conditions (presence of a primary key and deletion permissions).
- **Documentation**
	- Added a new label in the language file related to deleting system fields.

### CODE REVIEW

**Comment by sreehari2003** [comment]
I tried writing test for the same but browser is getting closed automatically when I reach the codeblock.

```ts

// Users/sreeharijayaraj/Documents/programming/nocodb/tests/playwright/pages/Dashboard/Grid/Column/index.ts   async 

verifySystemFieldIsNotDeletable() {
    const systemFields = ['Id', 'CreatedAt', 'UpdateAt'];
    Promise.all(
      systemFields.map(async column => {
        await this.get().page().getByTestId(column).locator('.ant-dropdown-trigger').click();
        await expect(
          this.get().page().locator('nc-menu-item').filter({
            hasText: 'Delete',
          })
        ).toBeHidden();
        await this.getColumnHeader(column).locator('div.ant-dropdown-trigger').locator('.nc-ui-dt-dropdown').click();
      })
    );
  }





//Users/sreeharijayaraj/Documents/programming/nocodb/tests/playwright/tests/db/columns/columnMenuOperations.spec.ts

  test.only('System fields should not be deletable', async () => {
    await dashboard.treeView.openTable({ title: 'Film' });
    await dashboard.grid.toolbar.fields.toggleShowSystemFields();
    await dashboard.grid.column.verifySystemFieldIsNotDeletable();
  });
 
 
 ```

**Review by dstala — CHANGES_REQUESTED** [review]
@sreehari2003 instead of removing delete option, it would be preferred to have it still in the menu - but keep it disabled. On hover- we can show tooltip `Deleting system field is not allowed`

**Comment by sreehari2003** [comment]
> @sreehari2003 instead of removing delete option, it would be preferred to have it still in the menu - but keep it disabled. On hover- we can show tooltip `Deleting system field is not allowed`

image

**Review by rameshmane7218 — APPROVED** [review]

**Comment by sreehari2003** [comment]
@DarkPhoenix2704  I have rebased the PR, please let me know if there are any additional modifications or adjustments needed.

**Pull request closed without merging**
