### PR TITLE
feat: migrate to nuxt 3 stable && bump deps

### PR DESCRIPTION
**Pull request by dammy001**
## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by wingkwong** [comment]
Suggest to discuss with the team members in discord first.

**Comment by dammy001** [comment]
> Suggest to discuss with the team members in discord first.

Okay.

**Comment by dammy001** [comment]
@wingkwong which channel can I get to discuss this on discord?

**Comment by wingkwong** [comment]
@dammy001 You may create a new issue in github first to explain the current problem(s) and the proposed solution(s). Then you can post the link in a new thread in `#general`.

**Comment by wingkwong** [comment]
Closing - not applicable. dependencies has been bumped in pnpm PR.

**Pull request closed without merging**
