### PR TITLE
fix: Project invite logic correction

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by wingkwong — APPROVED** [review]

**Review by wingkwong — COMMENTED** [review]
may double check if the corresponding test is there. if not, suggest to add it in this PR as well. cc @dstala.

**Comment by dstala** [comment]
> may double check if the corresponding test is there. if not, suggest to add it in this PR as well. cc @dstala.

What's new protocol? What's changed?

**Comment by pranavxc** [comment]
> > may double check if the corresponding test is there. if not, suggest to add it in this PR as well. cc @dstala.
> 
> What's new protocol? What's changed?

No UI changes in this PR, just corrected the logic. Before this PR it used to return from the beginning of the function call.

**Review by mertmit — APPROVED** [review]

**Comment by mertmit** [comment]
Merging this, I will discuss test cases with @dstala

**Pull request merged**
