### PR TITLE
feat: add URL formula

### LINKED ISSUE #1028: [Feature] [Bounty] Add clickable URL functionality to Formula column
Add Formula operator (i.e. "URL()") to make Formula result a clickable link.

**Need for this feature**
Enables dynamic (programmatic) link creation.  

For example open the appropriate IMDB page based on actor, movie ... or create links to open Desktop Applications (URI).

### PR DESCRIPTION
**Pull request by mertmit**
## Change Summary

Added a new formula called URL() which is compatible with other formulas.
Example usage: URL("https://google.com")

ref: closes #1028 

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)

## Test/ Verification

table
urlfield
urlfield2

## Additional information / screenshots (optional)

Uses URI::(url) syntax for handling URLs.

### CODE REVIEW

**Comment by o1lab** [comment]
Thank you for the enhancement.  We would need commit to be signed.

Please [see here](https://github.com/nocodb/nocodb/blob/master/.github/CONTRIBUTING.md#sign-your-existing-work).

**Comment by mertmit** [comment]
https://github.com/nocodb/nocodb/pull/1326#issuecomment-1047256880
I fixed it. Thanks for the help.

**Comment by wingkwong** [comment]
@mertmit It seems it only works in MySQL but not in other DBs. Below is the log when testing in a Postgres project.

```
select "test1326"."id" as "Id", 
"test1326"."created_at" as "CreatedAt", 
"test1326"."updated_at" as "UpdatedAt", 
"test1326"."name" as "name", CONCAT('URI::(',CONCAT('https://',"name"),')') 
as URL from "test1326"
```

image

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.12**

**Comment by mertmit** [comment]
https://github.com/nocodb/nocodb/pull/1326#issuecomment-1047728162

I think this problem is not related with my changes. There is a problem with uppercase column names when formula selected on postgre dbs. I achieved same result with precommit branch. I am going to look for a fix, I will be glad if you can try same example with lowercase and confirm it.

Both of this formula columns has 'CONCAT("test")' as formula and this is the result:
error

**Comment by wingkwong** [comment]
@mertmit Confirmed. I'll merge this PR first. For the upper case issue, I created a separate issue [#1332](https://github.com/nocodb/nocodb/issues/1332). I left some debug notes there. You may take a look. Thanks for the help!

**Review by wingkwong — APPROVED** [review]

**Comment by o1lab** [comment]
@mertmit : could you please help us with #1332 since you have more context.

**Comment by mertmit** [comment]
https://github.com/nocodb/nocodb/pull/1326#issuecomment-1048683795
Of course I already started working on it.

**Comment by wingkwong** [comment]
@all-contributors please add @mertmit  for code

**Comment by wingkwong** [comment]
@all-contributors please add @mertmit  for code

**Pull request merged**
