### PR TITLE
fix(nocodb): use is-inside-container to account for non-docker container runtime

### PR DESCRIPTION
**Pull request by wingkwong**
## Change Summary

- original: #5704 by @lhr0909

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by wingkwong** [comment]
@lhr0909 Can you help verify on the following image?

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.107.3-pr-5706-20230523-0543
```

Besides, the changes break the CI. Need to take a look.

**Comment by lhr0909** [comment]
> nocodb/nocodb-timely:0.107.3-pr-5706-20230523-0543

@wingkwong I am seeing an error on my end too. Could you provide a bit of instructions for building this docker image so I can potentially try on my end, just to make sure I didn't break anything? Thanks!

**Comment by wingkwong** [comment]
@lhr0909 You can build the local docker by executing `build-local-docker-image.sh` at root directory. You may verify if `isInsideContainer()` returns `true` on your side. Feel free to ping me at Discord if you need timely help - my ID is `wkw#3278`.

**Comment by wingkwong** [comment]
@lhr0909 The approach may not be correct. Lemme take it. Will create another PR later.

**Comment by wingkwong** [comment]
The new PR is [here](https://github.com/nocodb/nocodb/pull/5721)

**Comment by lhr0909** [comment]
> The new PR is [here](https://github.com/nocodb/nocodb/pull/5721)

I verified that the new approach works in my environment on FlyIO. Thank you so much!

**Pull request closed without merging**
