### PR TITLE
feat(nc-gui): toggle skeleton mode in erd when zooming out too far 

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

- when zooming out in ERD, show a more basic version of the flow (skeleton mode)

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

https://user-images.githubusercontent.com/78412429/195872423-8e41af7b-0cf2-4eeb-a38a-0422b3f99d2a.mov

https://user-images.githubusercontent.com/78412429/195872645-fd62232c-f8a7-48f6-bca3-fafa0a6757f6.mov

https://user-images.githubusercontent.com/78412429/195872525-123a2949-13d1-4dd4-89a9-7db2a307b034.mov

https://user-images.githubusercontent.com/78412429/195872573-2b4ce52e-ca85-49c2-a143-e66f644a3d56.mov

### CODE REVIEW

**Comment by bcakmakoglu** [comment]
Ignore the colors in the first videos. They've been removed as discussed.

https://user-images.githubusercontent.com/78412429/195906253-a6674add-0c99-4a34-8408-ca03901d9bd1.mov

https://user-images.githubusercontent.com/78412429/195906505-7e14861f-9bab-4627-9e20-5d942188dc1c.mov

**Comment by bcakmakoglu** [comment]
@mustafapc19 ping :)

**Comment by mustafapc19** [comment]
@bcakmakoglu Sorry I missed this. Really like this one. Does the edge info comes up when we hover over the label or over the edge?

**Comment by bcakmakoglu** [comment]
What info would you like to show? I'm not sure about the info but I could add it on hover 😄

**Comment by mustafapc19** [comment]
For info we could go with:

`Country`  has many `City`
`Film` many to many `Category` (This a bit grammatically incorrect but is simple to understand)

**Comment by mustafapc19** [comment]
Hover would be nice as its easier to discover for the user

**Comment by bcakmakoglu** [comment]
@mustafapc19 How about this?

https://user-images.githubusercontent.com/78412429/196029019-a5af196f-4bc6-43e5-a2a3-e9c3f145e535.mov

**Comment by mustafapc19** [comment]
@bcakmakoglu Table name would be better instead of using LTAR column names. 

And by hover I also meant edge color coming up on hover. But is it possible to do? Like label and edge color change on hover? Because right now label comes up but no idea which edge it is unless we select/click on it.

And I saw a minor issue with hover
image

**Comment by bcakmakoglu** [comment]
@mustafapc19 Overlapping edges over labels is sadly an issue that's not gonna be solved anytime soon.
It's an issue of element order and currently it's just the way it is. No fix.

Edge hover is implemented as discussed.

I have to disagree about table names for edges.
A Table with multiple edges to another Table (say Table A has 3 Edges going all to Table B) would say "Table A has many Table B" for *all* edges, which is not only redundant but useless info.

**Pull request merged**
