### PR TITLE
Correcting incorrect Korean translation

### PR DESCRIPTION
**Pull request by bsy0317**
## Change Summary

modified the Korean translation.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [■] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

### CODE REVIEW

**Comment by dstala** [comment]
@bsy0317 We use Crowdin for managing translations. Details here
https://docs.nocodb.com/engineering/translation/#how-to-add--edit-translations-

**Review by wingkwong — COMMENTED** [review]
we can take the change in `packages/nc-gui/lib/enums.ts`. For `packages/nc-gui/lang/ko.json`, please use crowdin instead.

**Comment by bsy0317** [comment]
Uploaded to crowdin. Thank you :)

**Comment by bsy0317** [comment]
Updated to crowdin. Is there anything I need to do separately in Github Action? I wonder when it will be reflected.

**Comment by bsy0317** [comment]
Updated to crowdin. Is there anything I need to do separately in Github Action? I wonder when it will be reflected.

**Comment by bsy0317** [comment]
Updated to crowdin. Is there anything I need to do separately in Github Action? I wonder when it will be reflected.

**Comment by bsy0317** [comment]
Updated to crowdin. Is there anything I need to do separately in Github Action? I wonder when it will be reflected.

**Comment by wingkwong** [comment]
@bsy0317 There is no action from your side. we've triggered a sync. See [here](https://github.com/nocodb/nocodb/pull/7032). The changes will be reflected once we merge the linked PR.

**Pull request closed without merging**
