### PR TITLE
Fixed: Form view do not extent text area

### PR DESCRIPTION
**Pull request by PyJim**
## Change Summary

Issue #5765 in Nocodb was resolved by addressing a problem with the 'nc-form-after-submit-msg' textarea. Previously, the textarea was not extending correctly, causing text overflow. To fix this, We added height: auto; and overflow: auto; to the nc-input.nc-cell-longtext class.. This solution ensures that users can now enter and view large messages within the textarea without any issues.

## Change type

- [x] fix: (bug fix for the user, not a fix to a build script)

## Test / Verification

To test and verify:

create text field
create form view
create share link
enter long text to the form using shared view

## Additional information / screenshots (optional)
textareaTEST

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by pranavxc — CHANGES_REQUESTED** [review]
Please exclude the `package-lock.json` if you are not adding/removing any dependency.

**Comment by PyJim** [comment]
package-lock.json excluded.

**Review by wingkwong — CHANGES_REQUESTED** [review]
@PyJim You are not excluding `package.json` but deleting, which is not expected. The expected file changed is `packages/nc-gui/pages/[projectType]/form/[viewId]/index.vue` only.

**Comment by PyJim** [comment]
Okay

**Comment by PyJim** [comment]
Please how do I exclude the package-lock.json file. Wanted to use the .gitignore file but it cannot be edited.

**Pull request closed without merging**
