### PR TITLE
fix(nc-gui): add google auth button to signin page

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

* add google auth btn to signin page
* update baseurl for google auth in signup page

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

image

### CODE REVIEW

**Comment by bcakmakoglu** [comment]
@vijayrathore8492 FYI :)

**Comment by bcakmakoglu** [comment]
@pranavxc @wingkwong ping :)

**Review by wingkwong — APPROVED** [review]
apply i18n or add a `TODO: i18n` for the line

```
Sign In with Google
```

**Comment by bcakmakoglu** [comment]
> `Sign In with Google`

@wingkwong updated with translation for `en`

**Pull request merged**
