### PR TITLE
feat: #1405 Latvian language support

### PR DESCRIPTION
**Pull request by OskarsPakers**
Signed-off-by: Oskars Pakers <oskars.pakers@gmail.com>

## Change Summary

Add latvian language support #1406

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by dstala** [comment]
@OskarsPakers
Could you please share i18n spreadsheet (copy or link) with updates done for Latvian language support? We will reflect those changes in our master spreadsheet.

**Comment by OskarsPakers** [comment]
@dstala  I haven`t updated any spreadsheets. What is the point of maintaining two places of translations? I updated only the JSON file.

**Comment by dstala** [comment]
> @dstala I haven`t updated any spreadsheets. What is the point of maintaining two places of translations? I updated only the JSON file.

we maintain i18n data in [master spreadsheet](https://docs.google.com/spreadsheets/d/1kGp92yLwhs1l7lwwgeor3oN1dFl7JZWuQOa4WSeZ0TE/edit#gid=2076107172) so that it becomes easier for everyone to propose quick changes without having to worry about the entire procedure &/ associated files to change.

thanks for helping nocodb i18n better. I have integrated your changes to the master spreadsheet. any further corrections/ suggestions, you can let us know.

**Comment by o1lab** [comment]
@all-contributors please add @OskarsPakers for code

**Pull request merged**
