### PR TITLE
🔦 Feature: Translation: "User acount Settings" pages  are translated in json file, but the newest release still keep untranslated

### PR DESCRIPTION
**Pull request by gitstart**
## Change Summary
#closes:  https://github.com/nocodb/nocodb/issues/5655

1, In latest release, "Full User acount Settings" pages are not tranlated. but Crodin translation page shows these phrases are already translated

2, columnTypes, such as "SingleLine Text", are NOT translate. but Crodin translation page shows these phrases are already translated

## Change type

- [x] feat: Translation: "User acount Settings" pages are translated in json file, but the newest release still keep untranslated

## Test/ Verification

Provide summary of changes.
https://www.loom.com/share/72125b95a84a47cabb757df6d9bb049e

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. You can just add translations to `en.json` for new entries. For other languages, please use crowdin. 
2. not all texts got translated still
image

**Comment by gitstart** [comment]
> 1. crowdin

What is the steps for adding translations to crowdin nocodb project?
we tried by uploading the en.json file but after successful upload the previous file still persists.

**Comment by wingkwong** [comment]
@gitstart See https://docs.nocodb.com/engineering/translation. 

In short, what you need to do is

- only commit `en.json`
- after this PR is merged to `develop`, include those translations in Crowdin, following the steps in the above link.

**Comment by gitstart** [comment]
> @gitstart See https://docs.nocodb.com/engineering/translation.
> 
> In short, what you need to do is
> 
> * only commit `en.json`
> * after this PR is merged to `develop`, include those translations in Crowdin, following the steps in the above link.

Changes requested have been attended to @wingkwong . Please review again.

**Review by wingkwong — CHANGES_REQUESTED** [review]
This PR includes lots of changes unrelated to the translation. Please either rebase or create a new PR with corresponding changes only.

**Comment by gitstart** [comment]
> This PR includes lots of changes unrelated to the translation. Please either rebase or create a new PR with corresponding changes only.

Hi @wingkwong cleaned up the PR in https://github.com/nocodb/nocodb/pull/6049

**Comment by wingkwong** [comment]
Closing this one - will be tracked in above PR.

**Pull request closed without merging**
