### PR TITLE
chore: add nuxi prepare script for generates types.

### PR DESCRIPTION
**Pull request by dammy001**
## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
What is the use case for adding such change? In development, running `npm run dev` would generate types automatically. Besides, in CI it has been also covered.

**Comment by dammy001** [comment]
@wingkwong

**Comment by wingkwong** [comment]
Then it should be included in `postinstall` as well.

**Comment by dammy001** [comment]
Nuxt will look out for this command if it's included it will run on postinstall

**Comment by wingkwong** [comment]
Oh ok. Verified. Didn't know that. Thanks.

**Pull request merged**
