### PR TITLE
refactor(gui-v2): make create and update project pages subpages of dashboard 

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

* Instead of navigating to blank pages with a single card, transition inside the dashboard (project list)
* Add slide transition to left sidebar
* Add hover effects to right sidebar items
* Add hover effects to bottom left sidebar 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [x] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by dstala** [comment]
@bcakmakoglu 

> Instead of navigating to blank pages with a single card, transition inside the dashboard (project list)
- [ ] IMO, border for text box can be gray (or light colored). feels slightly crowded with dark lines? or is it just because of my modified accent / theme; inner border for password field must go off
  
Screenshot 2022-08-22 at 1 51 56 PM

- [ ] Invite team @ top right intended?
  
 
Screenshot 2022-08-22 at 1 55 20 PM

**Comment by bcakmakoglu** [comment]
@dstala 
1. No the border shouldn't be so squeezed, I'll change that.
2. no idea where that comes from 😄

**Comment by bcakmakoglu** [comment]
@dstala my bad, the inputs do get a colored border - i can change that

**Comment by bcakmakoglu** [comment]
@dstala 
Updated

Apparently the button on the top right is intended - at least I didn't add it there, it was there already.
I updated it's styles so it doesn't look so out of place.

**Comment by dstala** [comment]
@bcakmakoglu 
- [x] looks great! liked this in-page transition.
  
Screenshot 2022-08-22 at 2 21 11 PM


- [ ] need `on hover` transition for `invite team`; would it make sense to just keep slightly bigger icon for `invite team` & place tool tip like other two buttons in that bar? we need to discuss overall purpose of keeping invite team in project-list page as
  - user invite is project specific; if we invite user, which project are we inviting for
  - shared base option, should we retain in this window?  
  - if we decide to retain : need to handle `user role` appropriately. that is - if an user is invited for a project as viewer, for him for that specific project, invite option shouldn't be visible
  
Screenshot 2022-08-22 at 2 19 08 PM

**Comment by bcakmakoglu** [comment]
@dstala I updated the PR again - the invite button isn't supposed to be seen in the header here.

**Comment by o1lab** [comment]
Lot of white space within the card on the left. 

Screenshot 2022-08-22 at 10 26 07

**Comment by o1lab** [comment]
Screenshot 2022-08-22 at 10 25 46

Input size is too wide. Should we make this as a dialog instead ? as we are only taking one input

**Comment by bcakmakoglu** [comment]
@o1lab Centered the create-external form a bit more and added a max-width to the other inputs.
If they're supposed to be modals or something else, let me know.

**Review by wingkwong — COMMENTED** [review]
Edit connection JSON dialog is commented out in this PR. Did you forget to update this part or will it be handled in another PR?

image

**Comment by bcakmakoglu** [comment]
@wingkwong I'll open a new PR for that

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
