### PR TITLE
fix: validate and sanitise column default value to avoid sql injection

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

- [x] Sanitise default value payload
    - [x] Accept only simple functions like `NOW()`, `UUID()`, etc ( vary depends on database )
    - [x] Treat `null`, boolean, number, CURRENT_TIMESTAMP as it is
    - [x] Sanitise single/double quoted string using knex
    - [x] Treat any other value as a string and sanitize using knex
- [x] Validate datatype and avoid SQL injection

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by wingkwong** [comment]
partially ref: #5225

**Review by wingkwong — COMMENTED** [review]
- better not to include `packages/nc-gui/components.d.ts` in this PR as it is not related to the changes.
- how about `packages/nocodb/src/db/sql-client/lib/snowflake/SnowflakeClient.ts`?

**Comment by pranavxc** [comment]
> * better not to include `packages/nc-gui/components.d.ts` in this PR as it is not related to the changes.
> * how about `packages/nocodb/src/db/sql-client/lib/snowflake/SnowflakeClient.ts`?

Done :+1:

**Review by wingkwong — APPROVED** [review]

**Comment by wingkwong** [comment]
Wait for CI/CD.

**Pull request merged**
