### PR TITLE
PR´s for: (Bug) #5103 and (Feature) #5103

### PR DESCRIPTION
**Pull request by semmjon**
## Change Summary

PR´s for:
    - https://github.com/nocodb/nocodb/issues/5105
    - https://github.com/nocodb/nocodb/issues/5103

The changes to the useProject.ts file modify the computed property bases to filter out any elements that have a false value for the enabled property.

The changes to the index.vue file include adding a new property baseId to a function call that opens a dialog box.

The changes to the tableApis.ts file modify the tableUpdate function to first check if the new table name is available before renaming the table.

The changes to the Model.ts file modify the checkTitleAvailable function to return true if the passed title is undefined or if no other model with the same title exists in the specified project and base.

## Change type

- [ x ] feat: (new feature for the user, not a new feature for build script)
- [ x ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Tested locally in a dev-scenario (npm run dev / run:watch) and in a deployed scenario with a dockerfile / helm-chart.

### CODE REVIEW

**Comment by semmjon** [comment]
A small recommendation on my part (on the side).
https://app.whatthediff.ai/repository/575307976/settings

**Comment by semmjon** [comment]
Sorry, I have now added my latest development improvements directly.

The following changes have been made:

Helm charts:
I have added the option to use MySQL.

Features:
I have implemented a new feature, which I have also described on this page: https://github.com/nocodb/nocodb/issues/5021.

Additionally, I have implemented a feature that was not previously documented:
This feature allows for a more dynamic way of importing Excel files. This includes the ability to handle files that have spaced lines before the table or an autoFilter active and to import the Excel header correctly. In the future, we can add the configuration "dynamicHeaders" to the Editor.vue Component (Checkbox).

Furthermore, I have taken the time to re-engineer the ExcelTemplateAdapter to write the code in a more readable and simplified version that is also more maintainable.

If I should remove some changes, please give me feedback :-)

In the future, I will try to create a pull request (PR) for each changed component more frequently.

**Comment by semmjon** [comment]
I will fix the unit tests as soon as possible :+1:

**Comment by semmjon** [comment]
OK. This Issue:
```
1) Rest
       Table
         Create table with same title:
```
Is not a bug anymore. Is the implemented feature to change only the table-alias when changing the table with the same title.

**Comment by wingkwong** [comment]
I don't see those 2 linked issues are related to each other. Please create two separate PRs instead of combining into one.

**Comment by semmjon** [comment]
Sorry, I'm a bit lazy there. I'll correct that right away (and the next time).

**Pull request closed without merging**
