### PR TITLE
fix: UI Inconsitency

### PR DESCRIPTION
**Pull request by DarkPhoenix2704**
## Change Summary

Updated styles for some components, matching other UI elements. 

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)
Check comments

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by DarkPhoenix2704** [comment]
@dstala Can you check and merge?

**Comment by dstala** [comment]
@DarkPhoenix2704 Help us with a quick note capturing summary of changes & screenshots if applicable highlighting the changes.

**Comment by DarkPhoenix2704** [comment]
Before
image
After
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by dstala** [comment]
> image image

We would like to retain the button as 'Primary' for this case & 
- `New` in data source
- Add New Token
- Invite team

Thanks for the PR. Will try out the changes later in the day & will let you know if there are any more changes needed.

**Comment by DarkPhoenix2704** [comment]
> We would like to retain the button as 'Primary' for this case &
> 
> * `New` in data source
> * Add New Token
> * Invite team
> 
> Thanks for the PR. Will try out the changes later in the day & will let you know if there are any more changes needed.

It's updated

**Comment by dstala** [comment]
Webhook save button not aligned with test-webhook button. rest of the changes are good. 
Screenshot 2023-05-12 at 7 43 25 PM

**Comment by DarkPhoenix2704** [comment]
@dstala Is there any public design file for NocoDb, I would like to work on further components

**Comment by dstala** [comment]
@DarkPhoenix2704 tests are failing. can you check?

**Comment by dstala** [comment]
@DarkPhoenix2704 
Below are steps to reproduce PW test failure issue

- Open http://localhost:3000/#/account/users/password-reset
- Feed incorrect 'current password'
- Should see error on submission; this error is missing in your PR

Screenshot from `develop`
Screenshot 2023-05-15 at 2 44 05 PM

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image
image

**Comment by DarkPhoenix2704** [comment]
image

**Pull request merged**
