### PR TITLE
feat(nc-gui): add survey mode option to share view

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

Provide summary of changes with issue number if any.

## Change type

- [x] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

- [ ] Verify survey mode option exists
- [ ] Verify link redirects to survey form
- [ ] Verify single form element is present
- [ ] Verify moving to each form element
- [ ] Verify submit

## Additional information / screenshots (optional)

https://user-images.githubusercontent.com/78412429/194128484-96569edc-e64b-4ba4-85cd-bcec20cc8ef7.mov

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
1. Survey form not showing after entering password

image

image

2. Weird tooltip message

image

**Comment by bcakmakoglu** [comment]
@wingkwong Use Theme means it's supposed to use the theme the project currently uses, i.e. primary and accent colors will be used for small details in the form (like ring colors or the main button).

**Comment by bcakmakoglu** [comment]
@wingkwong 

* Page loads normally now after password was entered

**Comment by bcakmakoglu** [comment]
@wingkwong 

* changed so that the form fetches project meta for the theme instead of copying it when generating a link

**Comment by bcakmakoglu** [comment]
@wingkwong 

I just realized that won't work because you can't fetch the project without having any credentials, so in a private tab it will just redirect to login 😅

I guess that's a limitation right now if you use the theme option, it doesn't update with the project theme - only when setting the link. Might be better to allow picking the colors in the option instead so it's not confusing.

**Comment by wingkwong** [comment]
Oh true. Then leave it.

**Review by dstala — COMMENTED** [review]
- [ ] Attachment cell, drag & drop didn't work
- [x] Password protected form, on clicking the first character says `password is required`
  
Screenshot 2022-10-06 at 3 39 56 PM

- [ ] Field description font appears too small in this layout. And paragraph can also be evenly spaced out.
  
Screenshot 2022-10-06 at 3 49 11 PM

**Comment by bcakmakoglu** [comment]
@dstala Comment seems to have gone somehow but the issues mentioned should be fixed.

* Dropzone works
* Alignment updated and font size slightly increased for field description
* Password validation does not occur until actually entering a password

**Comment by dstala** [comment]
> @dstala Comment seems to have gone somehow but the issues mentioned should be fixed.
> 
> * Dropzone works
> * Alignment updated and font size slightly increased for field description
> * Password validation does not occur until actually entering a password

Comments got hidden in PR list
Here's the link https://github.com/nocodb/nocodb/pull/3669#pullrequestreview-1132713498

**Comment by bcakmakoglu** [comment]
@dstala 
Thanks :)

Last point is fixed as well, if an invalid viewId is requested it redirects to the 404 page.

**Pull request merged**
