### PR TITLE
@author <Dean Lofts> <dean@deanlofts.xyz>

### PR DESCRIPTION
**Pull request by loftwah**

### CODE REVIEW

**Comment by o1lab** [comment]
@loftwah : thank you for the PR

Could you please sign the commits submitted. Below is how one of our user signed the commits which was already submitted.

https://user-images.githubusercontent.com/5435402/125443638-2ca54520-d72a-439b-93bc-4e2c692c759b.png

**Review by loftwah — COMMENTED** [review]
@author <Dean Lofts> <dean@deanlofts.xyz>

**Comment by loftwah** [comment]
Is that right? I found another example of @author <x> being added and did the same. There wasn't anyone in the file I modified prior to my change.

**Review by pranavxc — CHANGES_REQUESTED** [review]
Please sign all the commits and do a force push

you can refer following for more info - https://github.com/nocodb/nocodb/blob/master/contribute/HowToApplyLicense.md

**Comment by loftwah** [comment]
I think that is right now.

**Comment by o1lab** [comment]
@all-contributors please add @loftwah  for code

**Pull request merged**
