### PR TITLE
fix(nc-gui): correctly update tab after renaming table

### LINKED ISSUE #3893: 🐛 Bug: Table name inconsistent in UI when renamed
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a table
2. rename the table

### Desired Behavior

updated table name should be shown in UI

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.97.0**

### Attachements

Screenshot from 2022-10-01 13-14-32
Screenshot from 2022-10-01 13-12-34
Screenshot from 2022-10-01 13-11-45

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

* fixes #3893 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by wingkwong — APPROVED** [review]

**Comment by bcakmakoglu** [comment]
@dstala @o1lab 

I have an open question for this PR:
When I use the name `table_1` while renaming, the API will change it to `Table1` instead (as the Table title, the table name is actually `table_1` after renaming.

Now I am confused what should be the correct title? If the tab shows the table name it will be inconsistent with the tree view on the left because the tree view uses the table *title* not it's name 😄

**Comment by o1lab** [comment]
@pranavxc

**Comment by pranavxc** [comment]
In UI we are showing `title` everywhere which is an alias for the table and the actual table name is stored as `table_name`.

**Comment by bcakmakoglu** [comment]
@pranavxc 
Yeah, that I understood :)
But the confusion for a user or me appears when I *rename* a table, it will now show the new name I picked but the title that is generated from that name, i.e. if I rename `Table_0` to `Table_1` the title becomes `Table1` 
This PR will resolve that the new Tab is not using `Table_1` but the `Table1` title but it still seems confusing to me that the name I picked isn't used but instead a different title is given.

**Comment by pranavxc** [comment]
> @pranavxc Yeah, that I understood :) But the confusion for a user or me appears when I _rename_ a table, it will now show the new name I picked but the title that is generated from that name, i.e. if I rename `Table_0` to `Table_1` the title becomes `Table1` This PR will resolve that the new Tab is not using `Table_1` but the `Table1` title but it still seems confusing to me that the name I picked isn't used but instead a different title is given.

That looks like a bug then, earlier we just allowed updating `title` but recently we added support for updating the table name as well probably which is causing the problem.

**Comment by bcakmakoglu** [comment]
@pranavxc Should this PR still be merged or postponed then?
It would at least give consistency between Tabs and Tree view items after renaming.

**Comment by pranavxc** [comment]
> @pranavxc Should this PR still be merged or postponed then? It would at least give consistency between Tabs and Tree view items after renaming.



> @pranavxc Should this PR still be merged or postponed then? It would at least give consistency between Tabs and Tree view items after renaming

Go for the merge :+1:

**Pull request merged**
