### PR TITLE
Fixed #5765 : form view do not extent text area

### LINKED ISSUE #5765: 🐛 Bug: form view do not extent text area
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create text field
2. create form view
3. create share link
4. enter long text to the form using shared view

## Expected behavior

text ares should expand.

### Project Details

deployed on digitalocean server using docker

### Attachments

Screenshots

image

### PR DESCRIPTION
**Pull request by shashankvish0010**
## Change Summary

-Addressed an issue where the 'nc-form-after-submit-msg' textarea in Nocodb was not extending correctly, leading to text overflow. The problem was resolved by adding the 'overflow-auto' property to the 'nc-input' class, ensuring that users can now enter and view large messages within the textarea.
-fixed #5765 

## Change type

- [x] fix: (bug fix for the user, not a fix to a build script)

## Test/ Verification

To test and verify: 
- create text field
- create form view
- create share link
- enter long text to the form using shared view

## Additional information / screenshots (optional)

Screenshot (246)

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
Your change didn't solve the problem. Besides, the issue was about Shared Form View, not basic one.

image

**Comment by shashankvish0010** [comment]
Updated with all issues fixed with both normal and shared form view.

**Review by wingkwong — CHANGES_REQUESTED** [review]
Not aligned between form view & shared form view. To save time, please provide screenshots next time.

image

image

**Comment by wingkwong** [comment]
Closing - as it has been fixed in #6121.

**Pull request closed without merging**
