### PR TITLE
fix(nc-gui): dark mode styles for longtext field in form view

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

* ref: #4090 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
The dark mode styles for long text is ok.

Some other issues I've noticed while testing in this PR.

1. I think it's better to extend the width. In dark mode, I know where I should click. However, in light mode, if I click rightmost area, the input is not focused.

image

2. In the thank-you page, keep press enter and you will see `Saved successfully`.

image

**Comment by bcakmakoglu** [comment]
Ah thanks for pointing that put, I'll correct that :)

**Comment by bcakmakoglu** [comment]
@wingkwong Issues are fixed

**Review by wingkwong — CHANGES_REQUESTED** [review]
@bcakmakoglu The second one is still reproducible. I think some changes may be done here.

https://github.com/nocodb/nocodb/blob/d11cbde7f2b4d7afdc6707cd09faf14376369855/packages/nc-gui/pages/%5BprojectType%5D/form/%5BviewId%5D/index/survey.vue#L176

Besides, I think it's better to set a upper bound. 

image

**Comment by bcakmakoglu** [comment]
@wingkwong Whoops i forgot to exchange the submit fn ^^
Should be fine now.

Also set an upper limit of 5s for transitions.

**Review by wingkwong — APPROVED** [review]
All good.

**Pull request merged**
