### PR TITLE
feat: allow specifying db config through JSON string or JSON file

### PR DESCRIPTION
**Pull request by ejose19**
Related: https://github.com/nocodb/nocodb/issues/453#issuecomment-897821808

### CODE REVIEW

**Comment by ejose19** [comment]
Off topic, but you may want to apply prettier fixes so contributors can enable format on save (which makes the process less error prone).

**Review by pranavxc — CHANGES_REQUESTED** [review]
Please sign the commits, refer following link for more info - https://github.com/nocodb/nocodb/blob/master/contribute/HowToApplyLicense.md#how-to-sign-your-previous-work

**Comment by pranavxc** [comment]
@all-contributors please add @ejose19  for code

**Comment by dstala** [comment]
@ejose19 
[CLA assistant check](https://cla-assistant.io/nocodb/nocodb) <br/>Thank you for your contribution. Like many open-source projects, we request you to please sign our [Contributor License Agreement](https://cla-assistant.io/nocodb/nocodb). We really appreciate it & look forward to it.

**Pull request merged**
